- action:
  - alias: Update notifications
    data:
      message: Home Assistant  {{ states.updater.updater.state }}  is now available.
      title: New Home Assistant Release
    service: notify.ios
  alias: Home Assistant - Update Notifications
  id: '1501803740993'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - data:
      message: Home Assistant Started
    service: notify.ios_ryans_iphone
  alias: Home Assistant - Notify Ryan on Startup
  condition: []
  id: '1503944562866'
  trigger:
  - event: start
    platform: homeassistant
- id: '1537802654861'
  alias: HA - Heartbeat
  trigger:
  - platform: time
    minutes: /5
    seconds: 0
  condition: []
  action:
  - data:
      entity_id: input_boolean.homeassistant_heartbeat
    service: input_boolean.toggle
- id: '1537802946056'
  alias: HA - Node Red Heartbeat Watchdog
  trigger:
  - entity_id: automation.ha__heartbeat
    platform: state
  - entity_id: binary_sensor.heartbeat_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.heartbeat_status
    state: 'on'
  action:
  - data:
      message: Node Red heartbeat did not change within timeout. Please restart Node
        Red!
      title: Node Red Watchdog Expired!
    service: notify.ios_ryans_iphone
