- action:
  - data:
      message: Download Speed Low
    service: notify.ios
  alias: Speedtest - Time Warner Download
  id: '1499691067570'
  trigger:
  - below: '15'
    entity_id: sensor.speedtest_download
    platform: numeric_state
- action:
  - alias: Update notifications
    data:
      message: Home Assistant  {{ states.updater.updater.state }}  is now available.
      title: New Home Assistant Release
    service: notify.ios
  alias: Home Assistant - Update Notifications
  id: '1501803740993'
  trigger:
  - entity_id: updater.updater
    platform: state
- action:
  - alias: Set Subaru Distance Trigger
    data:
      payload: '100'
      qos: 1
      retain: 1
      topic: garage_ctl/car0/dist_trig
    service: mqtt.publish
  - alias: Set Corvette Distance Trigger
    data:
      payload: '100'
      qos: 1
      retain: 1
      topic: garage_ctl/car1/dist_trig
    service: mqtt.publish
  alias: Home Assistant - Set Parameters on Startup
  condition: []
  id: '1503199174152'
  trigger:
  - event: start
    platform: homeassistant
  - payload: started
    platform: mqtt
    topic: garage_state
- action:
  - data:
      entity_id: cover.garage_door
    service: cover.open_cover
  - data:
      message: Opening garage door based on available space.
    service: notify.ios
  alias: Garage Door - Open garage when Ryan arrives and space available
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: binary_sensor.subaru_parking
      state: 'off'
    - condition: state
      entity_id: binary_sensor.corvette_parking
      state: 'off'
  - condition: state
    entity_id: sensor.garage_door_state
    state: CLOSED
  id: '1503764090424'
  trigger:
  - entity_id: binary_sensor.ryan_home
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Garage controller connected
    service: notify.ios_ryans_iphone
  alias: Garage Door - Garage door controller connected
  condition: []
  id: '1503765196505'
  trigger:
  - payload: ''
    platform: mqtt
    topic: garage_state/started
- action:
  - data:
      entity_id: cover.garage_door
    service: cover.close_cover
  - data:
      message: Ryan is away. Closing garage door...
    service: notify.ios
  alias: Garage Door - Close door if Ryan is not home and space available
  condition:
  - condition: and
    conditions:
    - condition: or
      conditions:
      - condition: state
        entity_id: binary_sensor.subaru_parking
        state: 'off'
      - condition: state
        entity_id: binary_sensor.corvette_parking
        state: 'off'
    - condition: or
      conditions:
      - condition: state
        entity_id: sensor.garage_door_state
        state: OPENED
      - condition: state
        entity_id: sensor.garage_door_state
        state: OPENING
      - condition: state
        entity_id: sensor.garage_door_state
        state: STOPPED
      - condition: state
        entity_id: sensor.garage_door_state
        state: UNDEFINED
  id: '1503765780870'
  trigger:
  - entity_id: binary_sensor.ryan_away
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Home Assistant Started
    service: notify.ios_ryans_iphone
  alias: Home Assistant - Notify Ryan on Startup
  condition: []
  id: '1503944562866'
  trigger:
  - event: start
    platform: homeassistant
- action:
  - data_template:
      message: The UPS has reported a state change from {{trigger.from_state.state.title()}}
        to {{trigger.to_state.state.title()}}
      title: UPS Event
    service: notify.notify
  alias: UPS - Send notification state change
  condition: []
  id: '1507831314973'
  trigger:
  - entity_id: sensor.ups_status
    platform: state
- action:
  - data:
      message: Garage door is open and no one is home!
    service: notify.ios
  alias: Garage Door - Alert Household when garage is open for 15 minutes and no one
    is home
  condition:
  - condition: state
    entity_id: group.household
    state: not_home
  - condition: or
    conditions:
    - condition: state
      entity_id: sensor.garage_door_state
      state: OPENED
    - condition: state
      entity_id: sensor.garage_door_state
      state: OPENING
    - condition: state
      entity_id: sensor.garage_door_state
      state: STOPPED
    - condition: state
      entity_id: sensor.garage_door_state
      state: UNDEFINED
    - condition: state
      entity_id: sensor.garage_door_state
      state: OPENING
  id: '1511031537772'
  trigger:
  - minutes: /10
    platform: time
    seconds: 0
- action:
  - data:
      payload_template: '{{states(''input_number.touchpanel_brightness'')}}'
      topic: touchpanel/brightness
    service: mqtt.publish
  alias: Manually Set Touchpanel Brightness
  condition: []
  id: '1521688698723'
  trigger:
  - entity_id: input_number.touchpanel_brightness
    platform: state
- id: '1537802654861'
  alias: HA - Heartbeat
  trigger:
  - platform: time
    minutes: /5
    seconds: 0
  condition: []
  action:
  - data:
      entity_id: input_boolean.homeassistant_heartbeat
    service: input_boolean.toggle
- id: '1537802946056'
  alias: HA - Node Red Heartbeat Watchdog
  trigger:
  - entity_id: automation.ha__heartbeat
    platform: state
  - entity_id: binary_sensor.heartbeat_status
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.heartbeat_status
    state: 'on'
  action:
  - data:
      message: Node Red heartbeat did not change within timeout. Please restart Node
        Red!
      title: Node Red Watchdog Expired!
    service: notify.ios_ryans_iphone
