- platform: ring
  monitored_conditions:
  - ding
  - motion
  
- platform: mqtt
  state_topic: "garage_state/car0/state"
  name: "Subaru Parking Raw"
  device_class: occupancy

- platform: mqtt
  state_topic: "garage_state/car1/state"
  name: "Corvette Parking Raw"
  device_class: occupancy
  
- platform: apcupsd
- platform: mqtt
  state_topic: "securitySystem/sensor_0"
  name: "Security Sensor 0"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_1"
  name: "Security Sensor 1"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_2"
  name: "Security Sensor 2"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_3"
  name: "Security Sensor 3"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_4"
  name: "Security Sensor 4"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_5"
  name: "Security Sensor 5"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_6"
  name: "Security Sensor 6"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_7"
  name: "Security Sensor 7"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_8"
  name: "Security Sensor 8"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_9"
  name: "Security Sensor 9"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_10"
  name: "Security Sensor 10"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_11"
  name: "Security Sensor 11"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_12"
  name: "Security Sensor 12"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_13"
  name: "Security Sensor 13"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_14"
  name: "Security Sensor 14"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_15"
  name: "Security Sensor 15"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_16"
  name: "Security Sensor 16"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_17"
  name: "Security Sensor 17"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_18"
  name: "Security Sensor 18"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_19"
  name: "Security Sensor 19"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_20"
  name: "Security Sensor 20"
  device_class: lock
  payload_on: 1
  payload_off: 0

- platform: mqtt
  state_topic: "securitySystem/sensor_21"
  name: "Security Sensor 21"
  device_class: lock
  payload_on: 1
  payload_off: 0
  
- platform: trend
  sensors:
    master_bath_humidity_rising:
      friendly_name: Master Bathroom Humidity Rising
      entity_id: sensor.master_bathroom_multisensor_humidity
      max_samples: 4
      min_gradient: 0.002
      sample_duration: 60
      
    master_bath_temperature_rising:
      friendly_name: Master Bathroom Humidity Rising
      entity_id: sensor.master_bathroom_multisensor_temperature
      max_samples: 4
      min_gradient: 0.001
      sample_duration: 60

- platform: template
  sensors:
    security_ready:
      friendly_name: Security Ready
      device_class: safety
      value_template: >-
        {{    is_state('binary_sensor.security_sensor_0',  'on')
           or is_state('binary_sensor.security_sensor_1',  'on')
           or is_state('binary_sensor.security_sensor_2',  'on')
           or is_state('binary_sensor.security_sensor_3',  'on')
           or is_state('binary_sensor.security_sensor_4',  'on')
           or is_state('binary_sensor.security_sensor_5',  'on')
           or is_state('binary_sensor.security_sensor_6',  'on')
           or is_state('binary_sensor.security_sensor_8',  'on')
           or is_state('binary_sensor.security_sensor_10', 'on')
           or is_state('binary_sensor.water_heater_leak', 'on')
           or is_state('binary_sensor.hvac_leak', 'on') 
           or is_state('binary_sensor.office_window_east', 'on')
           or is_state('binary_sensor.office_window_west', 'on') 
           or is_state('binary_sensor.office_door', 'on') }}
           
    ryan_home:
      friendly_name: Ryan is home
      device_class: presence
      value_template: >-
         {{   is_state('device_tracker.ryannazaretian_ryans_iphone',  'home') }}
         {% if is_state('input_boolean.invert_ryan_away', 'off') %}
         {{ value }}
         {% else %}
         {{ not value }}
         {% endif %} 

        #{{    is_state('device_tracker.ryans_iphone',  'home') 
        #   or is_state('device_tracker.ryannazaretian_ryans_iphone',  'home')}} 
           
   # ryan_away:
   #   friendly_name: Ryan is away
   #   device_class: presence
   #   value_template: >-
   #     {%- set value = (is_state('device_tracker.ryans_iphone',  'not_home') or is_state('device_tracker.ryannazaretian_ryans_iphone',  'not_home')) -%}
   #     {% if is_state('input_boolean.invert_ryan_away', 'off') %}
   #     {{ value }}
   #     {% else %}
   #     {{ not value }}
   #     {% endif %}
  
    chelsea_home:
      friendly_name: Chelsea is home
      device_class: presence
      value_template: >-
        {{    is_state('device_tracker.chelseanazaretian_39beb247_0adb_4932_a6d0_de9c931ca779',  'home') }}
        {% if is_state('input_boolean.invert_chelsea_away', 'off') %}
        {{ value }}
        {% else %}
        {{ not value }}
        {% endif %}
#        {{    is_state('device_tracker.chelseanazaretian_39beb2470adb4932a6d0de9c931ca779',  'home')
#           or is_state('device_tracker.chelseas_iphone',  'home') }}
    
    
#    chelsea_away:
#      friendly_name: Chelsea is away
#      device_class: presence
#      value_template: >-
#        {%- set value = (is_state('device_tracker.chelseas_iphone',  'not_home') or is_state('device_tracker.chelseanazaretian_39beb2470adb4932a6d0de9c931ca779', 'not_home')) -%}
#        {% if is_state('input_boolean.invert_chelsea_away', 'off') %}
#        {{ value }}
#        {% else %}
#        {{ not value }}
#        {% endif %}
        
#    ryan_and_chelsea_away:
#      friendly_name: Ryan and Chelsea is away
#      value_template: >-
#        {{    is_state('binary_sensor.ryan_away',  'on')
#           and is_state('binary_sensor.chelsea_away',  'on') }}
    
    ryan_or_chelsea_home:
      friendly_name: Ryan or Chelsea is home
      value_template: >-
        {{    is_state('binary_sensor.ryan_home',  'on')
           or is_state('binary_sensor.chelsea_home',  'on') }}
      
           
    hvac_leak:
      friendly_name: HVAC Leak 
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_7')|int == 2}}"

    water_heater_leak:
      friendly_name: Water Heater Leak
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_9')|int == 2}}"
      
    dishwasher_leak:
      friendly_name: Dishwasher Leak
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_10')|int == 2}}"
      
    office_window_west:
      friendly_name: Office Window - West
      device_class: window
      value_template: "{{is_state('binary_sensor.neo_coolcam_doorwindow_detector_sensor_2', 'on')}}"
      
    office_window_east: 
      friendly_name: Office Window - East
      device_class: window
      value_template: "{{is_state('binary_sensor.neo_coolcam_doorwindow_detector_sensor', 'on')}}"  
      
    office_door:
      friendly_name: Office Door
      device_class: door
      value_template: "{{ is_state('sensor.vision_zd2105us5_recessed_doorwindow_sensor_alarm_level', '255') }}"
      
    master_bathroom_multisensor_motion:
      friendly_name: Master Bathroom Motion
      device_class: motion
      value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_alarm_level', '255') }}"
      
    away_mode:
      friendly_name: Away Mode
      value_template: "{{ is_state('input_select.house_mode', 'Away - Nighttime') or is_state('input_select.house_mode', 'Away - Daytime') }}"
      
    morning_mode: 
      friendly_name: Morning Mode
      value_template: "{{ is_state('input_select.house_mode', 'Home - Morning') }}"
      
    night_mode:
      friendly_name: Night Mode
      value_template: "{{ is_state('input_select.house_mode', 'Home - Nighttime') or is_state('input_select.house_mode', 'Away - Nighttime') or is_state('input_select.house_mode', 'Home - Morning') }}"
      
    heartbeat_status:
      friendly_name: Heartbeat Status
      device_class: problem
      value_template: "{{ (states.input_boolean.nodered_heartbeat.state) != (states.input_boolean.homeassistant_heartbeat.state) }}"
      delay_on:
        seconds: 2
      delay_off: 
        seconds: 2
    
    master_bathroom_occupancy:
      friendly_name: Master Bathroom Occupancy
      device_class: occupancy
      value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_alarm_level', '255') }}"
      delay_off:
        minutes: 5
        
    subaru_parking:
      friendly_name: "Subaru Parking"
      device_class: occupancy
      value_template: "{{ is_state('binary_sensor.subaru_parking_raw', 'on') }}"
      delay_off:
        minutes: 1

    corvette_parking:
      friendly_name: "Corvette Parking"
      device_class: occupancy
      value_template: "{{ is_state('binary_sensor.corvette_parking_raw', 'on') }}"
      delay_off:
        minutes: 1

- platform: workday
  country: US
  province: TX
          
      
      
    