- platform: template
  sensors:
    disable_ac:
      friendly_name: Window / Door Open for >=5 Minutes
      device_class: problem
      value_template: >-
        {{    is_state('binary_sensor.office_door',                     'on')
           or is_state('binary_sensor.garage_entry_door',               'on')
           or is_state('binary_sensor.front_door',                      'on')
           or is_state('binary_sensor.back_door_living_room_windows',   'on')
           or is_state('binary_sensor.kitchen_breakfast_nook_windows',  'on')
           or is_state('binary_sensor.utility_window',                  'on')
           or is_state('binary_sensor.north_bedroom_bathroom_windows',  'on')
           or is_state('binary_sensor.master_bedroom_bathroom_windows', 'on')
           or is_state('binary_sensor.office_window_east',              'on')
           or is_state('binary_sensor.office_window_west',              'on') }}
      delay_on:
        minutes: 5

    security_ready:
      friendly_name: Security Ready
      device_class: safety
      value_template: >-
        {{    is_state('binary_sensor.office_door',                     'on')
           or is_state('binary_sensor.garage_bay_door',                 'on')
           or is_state('binary_sensor.garage_entry_door',               'on')
           or is_state('binary_sensor.front_door',                      'on')
           or is_state('binary_sensor.back_door_living_room_windows',   'on')
           or is_state('binary_sensor.kitchen_breakfast_nook_windows',  'on')
           or is_state('binary_sensor.utility_window',                  'on')
           or is_state('binary_sensor.north_bedroom_bathroom_windows',  'on')
           or is_state('binary_sensor.master_bedroom_bathroom_windows', 'on')
           or is_state('binary_sensor.office_window_east',              'on')
           or is_state('binary_sensor.office_window_west',              'on') 
           or is_state('binary_sensor.smoke_detector',                  'on')
           or is_state('binary_sensor.dishwasher_leak',                 'on')
           or is_state('binary_sensor.water_heater_leak',               'on')
           or is_state('binary_sensor.hvac_leak',                       'on') }}
           
    ryan_home:
      friendly_name: Ryan is home
      device_class: presence
      value_template: >-
         {% set value = is_state('device_tracker.ryans_iphone', 'home') %}
         {% if is_state('input_boolean.invert_ryan_away', 'off') %}
         {{ value }}
         {% else %}
         {{ not value }}
         {% endif %} 
  
    chelsea_home:
      friendly_name: Chelsea is home
      device_class: presence
      value_template: >-
        {%  set value = is_state('device_tracker.chelseas_iphone', 'home') %}
        {% if is_state('input_boolean.invert_chelsea_away', 'off') %}
        {{ value }}
        {% else %}
        {{ not value }}
        {% endif %}
    
    ryan_or_chelsea_home:
      friendly_name: Ryan or Chelsea is home
      value_template: >-
        {{    is_state('binary_sensor.ryan_home',  'on')
           or is_state('binary_sensor.chelsea_home',  'on') }}
      
    hvac_leak:
      friendly_name: HVAC Leak 
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_7')|int == 2}}"

    water_heater_leak:
      friendly_name: Water Heater Leak
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_9')|int == 2}}"
      
    dishwasher_leak:
      friendly_name: Dishwasher Leak
      device_class: moisture
      value_template: "{{states('sensor.homeseer_unknown_type0201_id000a_flood_10')|int == 2}}"
      
    office_window_west:
      friendly_name: Office Window - West
      device_class: window
      value_template: "{{is_state('binary_sensor.neo_coolcam_doorwindow_detector_sensor_2', 'on')}}"
      
    office_window_east: 
      friendly_name: Office Window - East
      device_class: window
      value_template: "{{is_state('binary_sensor.neo_coolcam_doorwindow_detector_sensor', 'on')}}"  
      
    office_door:
      friendly_name: Office Door
      device_class: door
      value_template: "{{ is_state('sensor.vision_zd2105us5_recessed_doorwindow_sensor_alarm_level', '255') }}"
      
    master_bathroom_multisensor_motion:
      friendly_name: Master Bathroom Motion
      device_class: motion
      value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_alarm_level', '255') }}"
      
    away_mode:
      friendly_name: Away Mode
      value_template: "{{ is_state('input_select.house_mode', 'Away - Nighttime') or is_state('input_select.house_mode', 'Away - Daytime') }}"
      
    morning_mode: 
      friendly_name: Morning Mode
      value_template: "{{ is_state('input_select.house_mode', 'Home - Morning') }}"
      
    night_mode:
      friendly_name: Night Mode
      value_template: "{{ is_state('input_select.house_mode', 'Home - Nighttime') or is_state('input_select.house_mode', 'Away - Nighttime') or is_state('input_select.house_mode', 'Home - Morning') }}"
      
    heartbeat_status:
      friendly_name: Heartbeat Status
      device_class: problem
      value_template: "{{ (states.input_boolean.nodered_heartbeat.state) != (states.input_boolean.homeassistant_heartbeat.state) }}"
      delay_on:
        seconds: 2
      delay_off: 
        seconds: 2
    
    master_bathroom_occupancy:
      friendly_name: Master Bathroom Occupancy
      device_class: occupancy
      value_template: "{{ is_state('sensor.zooz_zse40_4in1_sensor_alarm_level', '255') }}"
      delay_off:
        minutes: 5
 
    left_side_parking:
      friendly_name: "Left Side Parking"
      device_class: occupancy
      value_template: '{{ states("sensor.left_vehicle_sensor")|float < states("input_number.left_car_distance_trigger")|float }} '
      delay_off: 
        seconds: 30
   
    right_side_parking:
      friendly_name: "Right Side Parking"
      device_class: occupancy
      value_template: '{{ states("sensor.right_vehicle_sensor")|float < states("input_number.right_car_distance_trigger")|float }}'
      delay_off: 
        seconds: 30
        
    power_importing:
      value_template: '{{ (states.sensor.net_consumption_now.state | float) > 0}}'
      friendly_name: 'Importing'
      
    power_exporting:
      value_template: '{{ (states.sensor.net_consumption_now.state | float) <= 0}}'
      friendly_name: 'Exporting'
      
      
- platform: workday
  country: US
  province: TX
          
- platform: nexia

- platform: octoprint
  monitored_conditions:
  - Printing
  - Printing Error   
  
- platform: zoneminder
    