#homeassistant:
#  # Name of the location where Home Assistant is running
#  name: Home
#  # Location required to calculate the time the sun rises and sets
#  latitude: !secret latitude
#  longitude: !secret longitude
#  # Impacts weather/sunrise data (altitude above sea level in meters)
#  elevation: !secret elevation
#  # metric for Metric, imperial for Imperial
#  unit_system: imperial
#  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
#  time_zone: America/Chicago
homeassistant:
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

# Enables map
map:

# Enables System Health
system_health:

api:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  # cors_allowed_origins:
  # add in the domain name or IP mentioned in the CORS error
  # - localhost


# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:

# Discover some devices automatically
# discovery:

# Include component files
automation: !include automations.yaml
binary_sensor: !include binary_sensor.yaml
camera: !include camera.yaml
climate: !include climate.yaml
cover: !include cover.yaml
device_tracker: !include device_tracker.yaml
fan: !include fan.yaml
input_boolean: !include input_boolean.yaml
input_datetime: !include input_datetime.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
light: !include light.yaml
media_player: !include media_player.yaml
notify: !include notify.yaml
panel_iframe: !include panel_iframe.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
switch: !include switch.yaml 
zone: !include zone.yaml

 
# apple_tv:
  # - host: !secret lr_apple_tv_ip
    # login_id: !secret lr_apple_tv_login_id
    # credentials: !secret lr_apple_tv_credentials
    # name: Living Room Apple TV

  # - host: !secret mbr_apple_tv_ip
    # login_id: !secret mbr_apple_tv_login_id
    # credentials: !secret mbr_apple_tv_credentials
    # name: Master Bedroom Apple TV
  
rachio:
  api_key: !secret rachio_api
  
speedtestdotnet:
  scan_interval:
    hours: 1
  
homekit:
  auto_start: False
  filter:
    include_domains:
      - alarm_control_panel
      - switch
      - light
      - cover
      - fan
      - climate
    include_entities:
      - switch.back_porch_lights
      - switch.desktop
      - switch.front_porch_lights
      - switch.front_yard_lighting
      - switch.kitchen_seasonal
      - switch.living_room_seasonal
      - switch.neato_schedule
      - light.dining_room_dimmer
      - light.master_bathroom_dimmer
      - light.kitchen_cabinet_lighting
      - fan.master_bathroom_ceiling_fan
      - cover.garage_door_cover
      - binary_sensor.garage_bay_door
      - binary_sensor.office_door
      - binary_sensor.garage_entry_door
      - binary_sensor.front_door
      - binary_sensor.back_door_living_room_windows
      - binary_sensor.kitchen_breakfast_nook_windows
      - binary_sensor.utility_window
      - binary_sensor.north_bedroom_bathroom_windows
      - binary_sensor.office_window_east
      - binary_sensor.office_window_west
      - binary_sensor.master_bedroom_bathroom_windows
      - binary_sensor.dishwasher_leak
      - binary_sensor.hvac_leak
      - binary_sensor.water_heater_leak
      - binary_sensor.smoke_detector
      - sensor.master_bathroom_multisensor_temperature
      - sensor.master_bathroom_multisensor_humidity
      - sensor.ups_internal_temperature
      - sensor.homeseer_unknown_type0201_id000a_temperature_9
      - sensor.homeseer_unknown_type0201_id000a_temperature_7
      - sensor.cpu_temp
      - climate.garage
      - climate.living_room
      - climate.mbdrm_office
      - sensor.outdoor_temperature
      - sensor.relative_humidity


    exclude_entities:
      - switch.siren
      - switch.rachio28c6ac_in_standby_mode
      - switch.back_lawn
      - switch.back_shrubs
      - switch.front_lawn
      - switch.front_shrubs
      - switch.retaining_wall
      - switch.driveway
      - switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch
      
  entity_config:
    alarm_control_panel.home_alarm:
      code: !secret alarm_code

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    entities:
      - sensor.load_15m
      - sensor.load_1m
      - sensor.load_5m
      - sensor.last_boot
      - input_boolean.homeassistant_heartbeat
      - input_boolean.nodered_heartbeat

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.load_15m
      - sensor.load_1m
      - sensor.load_5m
      - input_boolean.homeassistant_heartbeat
      - input_boolean.nodered_heartbeat

# Track the sun
sun:

# Ring
ring:
  username: !secret ring_username
  password: !secret ring_password

zwave:
  usb_path: /dev/ttyACM0

apcupsd:

neato:
  username: !secret neato_username
  password: !secret neato_password

panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave
  
cloud:

ios:

tts:
  - platform: google_translate

nexia:
  username: !secret nexia_username
  password: !secret nexia_password
  id: !secret home_id
  scan_interval: 30

recorder:
  db_url: sqlite:////config/home-assistant_v2.db
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    domains:
      - automation
      - weblink
      - updater

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    disarm_after_trigger: false
    triggered:
      pending_time: 
        seconds: 20
    disarmed:
      trigger_time: 
        seconds: 0
    armed_home:
      pending_time: 
        seconds: 0
      delay_time: 
        seconds: 0
    armed_away:
      pending_time: 
        seconds: 60
      delay_time:
        seconds: 0
        
octoprint:
  host: !secret octoprint_host
  api_key: !secret octoprint_api
  bed: true
  number_of_tools: 1
  
tesla: 
  username: !secret tesla_username
  password: !secret tesla_password
