- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
- platform: unifi
  host: localhost
  port: 8443
  verify_ssl: false
  username: !secret unifi_username
  password: !secret unifi_password