- platform: template
  fans:
    master_bathroom_ceiling_fan:
      friendly_name: Master Bathroom Ceiling Fan
      value_template: "{{ states('switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.enerwave_zwnrsm1_plussmart_single_relay_switch_module_switch
      