- platform: webostv
  host: !secret webos_ip
  mac:  !secret webos_mac
  name: Living Room TV
  
- platform: plex
  include_non_clients: true
  use_episode_art: true
  use_dynamic_groups: true
  scan_interval: 15
  host: !secret plex_ip
  port: !secret plex_port
  username: !secret plex_username
  password: !secret plex_password
  ssl: true
- platform: apple_tv
  name: Apple TV