# - platform: yr
  # monitored_conditions:
    # - temperature
    # - symbol
    # - precipitation
    # - windSpeed
    # - pressure
    # - windDirection
    # - humidity
    # - fog
    # - cloudiness
    # - lowClouds
    # - mediumClouds
    # - highClouds
    # - dewpointTemperature
    

   
- platform: ring
  monitored_conditions:
    - battery
    - last_activity
    - last_ding
    - last_motion
    - volume
    
- platform: mqtt
  state_topic: "garage_state/door_state"
  name: "Garage Door State"
  
- platform: mqtt
  state_topic: "garage_state/temperature"
  name: "Garage Temperature"
  unit_of_measurement: "°F"
  device_class: temperature
  
- platform: mqtt
  state_topic: "garage_state/car0/dist"
  name: "Subaru Sensor Distance"
  unit_of_measurement: "in"
  
- platform: mqtt
  state_topic: "garage_state/car1/dist"
  name: "Corvette Sensor Distance"
  unit_of_measurement: "in"
  
- platform: mqtt
  state_topic: "garage_state/car0/trigger"
  name: "Subaru Sensor Trigger"
  unit_of_measurement: "in"
  
- platform: mqtt
  state_topic: "garage_state/car1/trigger"
  name: "Corvette Sensor Trigger"
  unit_of_measurement: "in"
  
- platform: template
  sensors:
    subaru_occupancy:
      friendly_name: 'Subaru Occupancy'
      value_template: '{% if is_state("binary_sensor.subaru_parking", "on") %}Car In{% else %}Car Out{% endif %}'
      icon_template: '{% if is_state("binary_sensor.subaru_parking", "on") %}mdi:check-circle-outline{% else %}mdi:checkbox-blank-circle-outline{% endif %}'
    
    corvette_occupancy:
      friendly_name: 'Corvette Occupancy'
      value_template: '{% if is_state("binary_sensor.corvette_parking", "on") %}Car In{% else %}Car Out{% endif %}'
      icon_template: '{% if is_state("binary_sensor.corvette_parking", "on") %}mdi:check-circle-outline{% else %}mdi:checkbox-blank-circle-outline{% endif %}'
    
    ups_load_watts:
      friendly_name: 'UPS Load'
      value_template: "{{ states('sensor.ups_load')|float * 5.0}}"
      unit_of_measurement: 'watts'
      
    hvac_zwave_battery:
      friendly_name: 'HVAC Z-Wave Battery Level'
      value_template: "{{ state_attr('zwave.homeseer_unknown_type0201_id000a_7', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery

    water_heater_zwave_battery:
      friendly_name: 'Water Heater Z-Wave Battery Level'
      value_template: "{{ state_attr('zwave.homeseer_unknown_type0201_id000a_9', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
    
    neato_battery:
      friendly_name: 'Neato Battery Level'
      value_template: "{{ state_attr('vacuum.neato', 'battery_level') }}"
      icon_template: "{{ state_attr('vacuum.neato', 'battery_icon') }}"
      unit_of_measurement: '%'
      device_class: battery
      
    office_window_west_zwave_battery:
      friendly_name: 'Office Windows - West Battery Level'
      value_template: "{{ state_attr('zwave.neo_coolcam_doorwindow_detector', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
      
    office_window_east_zwave_battery:
      friendly_name: 'Office Windows - East Battery Level'
      value_template: "{{ state_attr('zwave.neo_coolcam_doorwindow_detector_2', 'battery_level') }}"
      unit_of_measurement: '%'
      device_class: battery
      
    master_bathroom_multisensor_humidity:
      friendly_name: Master Bathroom Humidity 
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.zooz_zse40_4in1_sensor_relative_humidity') }}"
      device_class: humidity
      
    master_bathroom_multisensor_temperature:
      friendly_name: Master Bathroom Temperature 
      unit_of_measurement: "°F"
      value_template: "{{ states('sensor.zooz_zse40_4in1_sensor_temperature') }}"
      device_class: temperature
      
    master_bathroom_multisensor_battery:
      friendly_name: Master Bathroom Battery 
      unit_of_measurement: "%"
      value_template: "{{ state_attr('zwave.zooz_zse40_4in1_sensor', 'battery_level') }}"
      device_class: battery
      
    master_bathroom_multisensor_illuminance:
      friendly_name: Master Bathroom Battery 
      unit_of_measurement: "%"
      value_template: "{{ states('sensor.zooz_zse40_4in1_sensor_luminance') }}"
      device_class: illuminance
      
    office_door_battery:
      friendly_name: Office Door Battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('zwave.vision_zd2105us5_recessed_doorwindow_sensor', 'battery_level') }}"
      device_class: battery
    
    dishwasher_battery:
      friendly_name: Dishwasher Battery
      unit_of_measurement: "%"
      value_template: "{{ state_attr('zwave.dishwasher_leak', 'battery_level') }}"
      device_class: battery
      
- platform: command_line
  name: CPU Temp
  command: "/bin/cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "ºC"
  value_template: '{{ value | multiply(0.001) }}'
- platform: systemmonitor
  resources:
    - type: memory_use_percent
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: last_boot
    
- platform: apcupsd
  resources:
    - bcharge
    - linev
    - loadpct
    - numxfers
    - outputv
    - status
    - timeleft
    - tonbatt
    - itemp
    - battv
    - lastxfer
    
- platform: plex
  username: !secret plex_username
  password: !secret plex_password
  
- platform: darksky
  api_key: !secret darksky
  forecast: 
    - 0
  monitored_conditions:
    - summary
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - icon
    