- platform: wake_on_lan
  # Desktop
  name: "Desktop"
  mac_address: !secret desktop_mac
  host: !secret desktop_ip
  retain: true
  
- platform: template
  switches:
    siren:
      friendly_name: Siren
      value_template: "{{ is_state('switch.gr_unknown_type0003_id0003_switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.gr_unknown_type0003_id0003_switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.gr_unknown_type0003_id0003_switch
          
    front_porch_lights:
      friendly_name: Front Porch Lights
      value_template: "{{ is_state('switch.switch', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
          entity_id: switch.switch
      turn_off:
        service: switch.turn_off
        data:
          entity_id: switch.switch
  

