- platform: wake_on_lan
  # Desktop
  name: "Desktop"
  mac_address: !secret desktop_mac
  host: !secret desktop_ip
  retain: true
  
- platform: rachio

- platform: tplink
  name: Ben's Lamp
  host: 192.168.1.21
- platform: tplink
  name: Master Bedroom Lamp
  host: 192.168.1.22


